/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#79545c",
        "on-primary": "#ffffff",
        "primary-container": "#e2b4bd",
        "on-primary-container": "#67444c",
        "primary-fixed": "#ffd9e0",
        "primary-fixed-dim": "#e9bbc4",
        "on-primary-fixed": "#2e131a",
        "on-primary-fixed-variant": "#5f3d45",
        "secondary": "#715954",
        "on-secondary": "#ffffff",
        "secondary-container": "#f9d8d2",
        "on-secondary-container": "#765d58",
        "secondary-fixed": "#fcdbd5",
        "secondary-fixed-dim": "#dfbfba",
        "on-secondary-fixed": "#291714",
        "on-secondary-fixed-variant": "#58413d",
        "tertiary": "#2c694e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8fcdac",
        "on-tertiary-container": "#19583f",
        "tertiary-fixed": "#b1f0ce",
        "tertiary-fixed-dim": "#95d4b3",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#0e5138",
        "surface": "#fbf9f8",
        "surface-dim": "#dbd9d9",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e2",
        "surface-variant": "#e4e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#4f4446",
        "on-background": "#1b1c1c",
        "background": "#fbf9f8",
        "outline": "#817476",
        "outline-variant": "#d3c2c5",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-tint": "#79545c",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f2f0f0",
        "inverse-primary": "#e9bbc4",
        "status-listed-bg": "#f1f5f9",
        "status-listed-text": "#475569",
        "status-matched-bg": "#e3f2fd",
        "status-matched-text": "#1565c0",
        "status-accepted-bg": "#e8f5e9",
        "status-accepted-text": "#1b5e20",
        "status-pickup-bg": "#fff8e1",
        "status-pickup-text": "#ff6f00",
        "status-transit-bg": "#fff3e0",
        "status-transit-text": "#e65100",
        "status-delivered-bg": "#e8f5e9",
        "status-delivered-text": "#1b5e20",
        "status-confirmed-bg": "#f3e5f5",
        "status-confirmed-text": "#6a1b9a",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "2rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-2xl": "3rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "sans": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-sm": ["Atkinson Hyperlegible Next"],
        "body-md": ["Atkinson Hyperlegible Next"],
        "label-sm": ["Atkinson Hyperlegible Next"],
        "label-md": ["Atkinson Hyperlegible Next"],
        "label-lg": ["Atkinson Hyperlegible Next"],
        "display": ["Bricolage Grotesque", "sans-serif"],
        "display-lg": ["Bricolage Grotesque"],
        "headline-sm": ["Bricolage Grotesque"],
        "headline-md": ["Bricolage Grotesque"],
        "headline-lg": ["Bricolage Grotesque"]
      },
      fontSize: {
        'display-lg': ['2.25rem', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.015em' }],
        'headline-lg': ['1.75rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['1.375rem', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.35', fontWeight: '600' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.55', fontWeight: '400' }],
        'body-md': ['0.95rem', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['1rem', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['0.875rem', { lineHeight: '1.4', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
      },
      boxShadow: {
        'elevated': '0 8px 24px rgba(79, 68, 70, 0.14)',
        'card': '0 1px 6px rgba(79, 68, 70, 0.06)',
        'xs': '0 1px 2px rgba(79, 68, 70, 0.05)',
        'sm': '0 1px 3px rgba(79, 68, 70, 0.08)',
      },
    },
  },
  plugins: [],
}