/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#0d1c2e",
        "outline-variant": "#bfc9bf",
        "tertiary-container": "#005b3d",
        "surface-container-lowest": "#ffffff",
        "primary": "#004226",
        "on-secondary-container": "#663500",
        "secondary-fixed": "#ffdcc3",
        "inverse-on-surface": "#eaf1ff",
        "on-primary": "#ffffff",
        "surface-tint": "#246b46",
        "on-surface-variant": "#404942",
        "inverse-primary": "#8fd6a9",
        "on-primary-fixed": "#002110",
        "secondary": "#904d00",
        "surface-variant": "#d5e3fc",
        "surface-container": "#e6eeff",
        "on-tertiary": "#ffffff",
        "outline": "#707971",
        "background": "#f8f9ff",
        "on-primary-fixed-variant": "#005230",
        "on-background": "#0d1c2e",
        "surface": "#f8f9ff",
        "on-tertiary-container": "#47d99e",
        "on-primary-container": "#8ad1a4",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary-fixed": "#aaf2c4",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-container": "#fe932c",
        "surface-container-highest": "#d5e3fc",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed-variant": "#6e3900",
        "on-secondary-fixed": "#2f1500",
        "primary-container": "#0f5b38",
        "surface-container-low": "#eff4ff",
        "tertiary": "#00412b",
        "inverse-surface": "#233144",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#8fd6a9",
        "surface-dim": "#ccdbf3",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-high": "#dce9ff",
        "secondary-fixed-dim": "#ffb77d",
        "on-error-container": "#93000a",
        // Status colors from spec
        "status-listed-bg": "#f1f5f9",
        "status-listed-text": "#475569",
        "status-matched-bg": "#e3f2fd",
        "status-matched-text": "#1565c0",
        "status-accepted-bg": "#e8f5e9",
        "status-accepted-text": "#1b5e20",
        "status-pickup-bg": "#fff8e1",
        "status-pickup-text": "#ff6f00",
        "status-transit-bg": "#fff3e0",
        "status-transit-text": "#e65100",
        "status-delivered-bg": "#e8f5e9",
        "status-delivered-text": "#1b5e20",
        "status-confirmed-bg": "#f3e5f5",
        "status-confirmed-text": "#6a1b9a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "2rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-2xl": "3rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "sans": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-lg": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        'headline-md': ['1.125rem', { lineHeight: '1.5', fontWeight: '700' }],
        'headline-sm': ['1.0625rem', { lineHeight: '1.5', fontWeight: '700' }],
        'headline-lg': ['1.375rem', { lineHeight: '1.4', fontWeight: '700' }],
        'body-md': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['0.75rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['0.875rem', { lineHeight: '1.5', fontWeight: '500' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.5', fontWeight: '500' }],
        'label-lg': ['1rem', { lineHeight: '1.5', fontWeight: '500' }],
      },
      boxShadow: {
        'elevated': '0 4px 16px rgba(15, 91, 56, 0.4)',
        'card': '0 1px 6px rgba(0, 0, 0, 0.03)',
        'xs': '0 1px 2px rgba(0, 0, 0, 0.05)',
        'sm': '0 1px 3px rgba(0, 0, 0, 0.1)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(to bottom right, #0F5B38, #005B3D, #004226)',
      },
    },
  },
  plugins: [],
}