"""add location_unknown to deliveries

Revision ID: 3b8d638a3e25
Revises: 51f3ee1cdc9e
Create Date: 2026-10-06 16:23:02.113767

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8d638a3e25'
down_revision: Union[str, None] = '51f3ee1cdc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('location_unknown', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'location_unknown')
    # ### end Alembic commands ###